version: '3.9'
services:
  namesrv:
    image: pyaar-repository-registry.ap-southeast-1.cr.aliyuncs.com/pyaar/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-namesrv
    command: sh bin/mqnamesrv
    environment:
      - NAMESRV_JVM_XMS=2g
      - NAMESRV_JVM_XMX=2g
      - NAMESRV_JVM_XMN=1g
    network_mode: host

  broker-c0-n1:
    image: pyaar-repository-registry.ap-southeast-1.cr.aliyuncs.com/pyaar/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-broker-c0-n1
    command: sh bin/mqbroker -c /home/rocketmq/rocketmq-4.9.2/conf/broker.conf
    environment:
      - NAMESRV_ADDR=${NAMESRV_ADDR}
      - BROKER_JVM_XMS=8g
      - BROKER_JVM_XMX=8g
    volumes:
      - ./broker-c0-n1.conf:/home/rocketmq/rocketmq-4.9.2/conf/broker.conf
      - ./store-c0-n1:/home/rocketmq/rocketmq-4.9.2/store
    network_mode: host

  broker-c1-n1:
    image: pyaar-repository-registry.ap-southeast-1.cr.aliyuncs.com/pyaar/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-broker-c1-n1
    command: sh bin/mqbroker -c /home/rocketmq/rocketmq-4.9.2/conf/broker.conf
    environment:
      - NAMESRV_ADDR=${NAMESRV_ADDR}
      - BROKER_JVM_XMS=8g
      - BROKER_JVM_XMX=8g
    volumes:
      - ./broker-c1-n1.conf:/home/rocketmq/rocketmq-4.9.2/conf/broker.conf
      - ./store-c1-n1:/home/rocketmq/rocketmq-4.9.2/store
    network_mode: host

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=${NAMESRV_ADDR} -Dserver.port=8085
    network_mode: host