version: '3.9'
services:
  redis-group2-m0:
    container_name: redis-group2-m0
    image: redis:${REDIS_VERSION}
    restart: always
    command:
      - /etc/redis.conf
    network_mode: host
    volumes:
      - ./conf/group2/redis-m0.conf:/etc/redis.conf
      - ./data/group2/m0:/data

  redis-group3-s1:
    container_name: redis-group3-s1
    image: redis:${REDIS_VERSION}
    restart: always
    command:
      - /etc/redis.conf
    network_mode: host
    volumes:
      - ./conf/group3/redis-s1.conf:/etc/redis.conf
      - ./data/group3/s1:/data

  redis-group1-s2:
    container_name: redis-group1-s2
    image: redis:${REDIS_VERSION}
    restart: always
    command:
      - /etc/redis.conf
    network_mode: host
    volumes:
      - ./conf/group1/redis-s2.conf:/etc/redis.conf
      - ./data/group1/s2:/data

