version: '3.9'
services:
  nginx:
    image: nginx:1.20.2
    container_name: nginx
    restart: always
    volumes:
      - ./conf:/etc/nginx
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"